modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-SA 4.0"
issueTrackerURL="https://github.com/Chuzume/Craftsmans-Bows/issues"
[[mods]]
modId="craftsman_bows"
version="1.1.3"
displayName="Craftsman's Bows"
description='''
    Add some vanilla-like ranged weapons.
'''
authors="Chuzume"
credits="Thanks to all contributors!"
logoFile="assets/craftsman_bows/icon.png"
displayURL="https://fabricmc.net/"

[[dependencies.craftsman_bows]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftsman_bows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
