modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Chuzume/Craftsmans-Bows/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Chuzume/Craftsmans-Bows"
logoFile="assets/craftsman_bows/icon.png"
credits="Sounds in the \"erdie\" folder: by Erdie (https://freesound.org/people/Erdie/) / Sounds in the \"dungeons\" folder: from Minecraft Dungeons by Mojang"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
